language: android
android:
  components:
    - platform-tools
    - build-tools-28.0.1
    - android-23
    - extra-android-support

install: ant


addons:
  apt:
    packages:
      - ant
jdk: oraclejdk8

notifications:
  email: false

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin > /dev/null 2>/dev/null
  - chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - mv android-ndk-r10e android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - git submodule update --init --recursive
script:
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 NDK_DEBUG=0 V=1 -j2 APP_CFLAGS="-w"
  - ant release
  - curl --upload-file bin/poke646-release-unsigned.apk https://transfer.sh/poke646-release-unsigned.apk

